"""Regenerate lib/elections/eavs-2024-registration.ts from the EAC 2024 EAVS public-release CSV.

Usage: python3 scripts/build-eavs-registration.py
Sums A1a (total registered), A1b (active) and A1c (inactive) over every reporting
jurisdiction in each state/territory. Negative values are EAVS missing-data codes
and are excluded; the count of jurisdictions without an A1a value is kept.
"""
import csv
import hashlib
import io
import json
import urllib.request
import zipfile

URL = "https://www.eac.gov/sites/default/files/2025-06/2024_EAVS_for_Public_Release_nolabel_V1_csv.zip"
OUT = "lib/elections/eavs-2024-registration.ts"

req = urllib.request.Request(URL, headers={"User-Agent": "Mozilla/5.0 (brain-lab election-source monitor)"})
blob = urllib.request.urlopen(req, timeout=120).read()
digest = hashlib.sha256(blob).hexdigest()
zf = zipfile.ZipFile(io.BytesIO(blob))
name = next(n for n in zf.namelist() if n.endswith(".csv"))

agg = {}
for row in csv.DictReader(io.TextIOWrapper(zf.open(name), encoding="latin-1")):
    a = agg.setdefault(row["State_Abbr"], {"jurisdictions": 0, "reported": 0, "total": 0, "active": 0, "inactive": 0})
    a["jurisdictions"] += 1
    for key, col in (("total", "A1a"), ("active", "A1b"), ("inactive", "A1c")):
        try:
            v = float(row[col])
        except ValueError:
            v = -1
        if v >= 0:
            a[key] += int(v)
            if key == "total":
                a["reported"] += 1

rows = {k: agg[k] for k in sorted(agg)}
with open(OUT, "w") as f:
    f.write("// Generated by scripts/build-eavs-registration.py. Do not edit by hand.\n")
    f.write('import type { EavsRegistrationRow } from "./registration";\n\n')
    f.write("export const EAVS_2024_SOURCE = " + json.dumps({
        "publisher": "U.S. Election Assistance Commission",
        "survey": "2024 Election Administration and Voting Survey (EAVS), public release V1",
        "url": URL,
        "codebookUrl": "https://www.eac.gov/sites/default/files/2025-06/2024_EAVS_Codebook.xlsx",
        "landingUrl": "https://www.eac.gov/research-and-data/datasets-codebooks-and-surveys",
        "asOf": "2024 general election (November 5, 2024)",
        "sha256": digest,
    }, indent=2) + " as const;\n\n")
    f.write("export const EAVS_2024_REGISTRATION: Record<string, EavsRegistrationRow> = " + json.dumps(rows, indent=2) + ";\n")
print(f"wrote {OUT}: {len(rows)} jurisdictions, sha256 {digest}")
