// Generated by scripts/build-eavs-registration.py. Do not edit by hand.
import type { EavsRegistrationRow } from "./registration";

export const EAVS_2024_SOURCE = {
  "publisher": "U.S. Election Assistance Commission",
  "survey": "2024 Election Administration and Voting Survey (EAVS), public release V1",
  "url": "https://www.eac.gov/sites/default/files/2025-06/2024_EAVS_for_Public_Release_nolabel_V1_csv.zip",
  "codebookUrl": "https://www.eac.gov/sites/default/files/2025-06/2024_EAVS_Codebook.xlsx",
  "landingUrl": "https://www.eac.gov/research-and-data/datasets-codebooks-and-surveys",
  "asOf": "2024 general election (November 5, 2024)",
  "sha256": "7e04f8edc5a11c54b5692e714bc31f6e3609436af4c50ba1d4e5679f74486743"
} as const;

export const EAVS_2024_REGISTRATION: Record<string, EavsRegistrationRow> = {
  "AK": {
    "jurisdictions": 1,
    "reported": 1,
    "total": 611078,
    "active": 565242,
    "inactive": 45836
  },
  "AL": {
    "jurisdictions": 67,
    "reported": 67,
    "total": 3868040,
    "active": 3466606,
    "inactive": 401434
  },
  "AR": {
    "jurisdictions": 75,
    "reported": 75,
    "total": 1835723,
    "active": 1359659,
    "inactive": 476064
  },
  "AS": {
    "jurisdictions": 1,
    "reported": 1,
    "total": 15948,
    "active": 15948,
    "inactive": 0
  },
  "AZ": {
    "jurisdictions": 15,
    "reported": 15,
    "total": 5075337,
    "active": 4366786,
    "inactive": 708551
  },
  "CA": {
    "jurisdictions": 58,
    "reported": 58,
    "total": 25720597,
    "active": 22836602,
    "inactive": 2883995
  },
  "CO": {
    "jurisdictions": 64,
    "reported": 64,
    "total": 4583280,
    "active": 4074612,
    "inactive": 508668
  },
  "CT": {
    "jurisdictions": 169,
    "reported": 169,
    "total": 2520650,
    "active": 2292818,
    "inactive": 227832
  },
  "DC": {
    "jurisdictions": 1,
    "reported": 1,
    "total": 612904,
    "active": 469969,
    "inactive": 142935
  },
  "DE": {
    "jurisdictions": 3,
    "reported": 3,
    "total": 788441,
    "active": 742370,
    "inactive": 46071
  },
  "FL": {
    "jurisdictions": 67,
    "reported": 67,
    "total": 15740083,
    "active": 14028831,
    "inactive": 1708841
  },
  "GA": {
    "jurisdictions": 159,
    "reported": 159,
    "total": 8234335,
    "active": 7174961,
    "inactive": 1059374
  },
  "GU": {
    "jurisdictions": 1,
    "reported": 1,
    "total": 62098,
    "active": 62098,
    "inactive": 0
  },
  "HI": {
    "jurisdictions": 5,
    "reported": 4,
    "total": 861333,
    "active": 765998,
    "inactive": 95335
  },
  "IA": {
    "jurisdictions": 99,
    "reported": 99,
    "total": 2256774,
    "active": 2016967,
    "inactive": 239807
  },
  "ID": {
    "jurisdictions": 44,
    "reported": 44,
    "total": 1178750,
    "active": 1178750,
    "inactive": 0
  },
  "IL": {
    "jurisdictions": 108,
    "reported": 108,
    "total": 8970541,
    "active": 8104485,
    "inactive": 817109
  },
  "IN": {
    "jurisdictions": 92,
    "reported": 92,
    "total": 4840856,
    "active": 4288091,
    "inactive": 552765
  },
  "KS": {
    "jurisdictions": 105,
    "reported": 105,
    "total": 2031119,
    "active": 1871857,
    "inactive": 159262
  },
  "KY": {
    "jurisdictions": 120,
    "reported": 120,
    "total": 3548136,
    "active": 3219361,
    "inactive": 328775
  },
  "LA": {
    "jurisdictions": 64,
    "reported": 64,
    "total": 3046376,
    "active": 2734059,
    "inactive": 312317
  },
  "MA": {
    "jurisdictions": 351,
    "reported": 351,
    "total": 5142343,
    "active": 4369280,
    "inactive": 773063
  },
  "MD": {
    "jurisdictions": 24,
    "reported": 24,
    "total": 4555217,
    "active": 4231112,
    "inactive": 320634
  },
  "ME": {
    "jurisdictions": 497,
    "reported": 489,
    "total": 1223468,
    "active": 1041826,
    "inactive": 181642
  },
  "MI": {
    "jurisdictions": 83,
    "reported": 83,
    "total": 8440236,
    "active": 7267666,
    "inactive": 1172570
  },
  "MN": {
    "jurisdictions": 87,
    "reported": 87,
    "total": 3853668,
    "active": 3853668,
    "inactive": 0
  },
  "MO": {
    "jurisdictions": 116,
    "reported": 116,
    "total": 4388787,
    "active": 4075977,
    "inactive": 312810
  },
  "MP": {
    "jurisdictions": 1,
    "reported": 1,
    "total": 19329,
    "active": 19329,
    "inactive": 0
  },
  "MS": {
    "jurisdictions": 82,
    "reported": 82,
    "total": 2131726,
    "active": 1965948,
    "inactive": 165778
  },
  "MT": {
    "jurisdictions": 56,
    "reported": 56,
    "total": 800573,
    "active": 691534,
    "inactive": 107822
  },
  "NC": {
    "jurisdictions": 100,
    "reported": 100,
    "total": 7854464,
    "active": 6986365,
    "inactive": 853624
  },
  "ND": {
    "jurisdictions": 53,
    "reported": 0,
    "total": 0,
    "active": 0,
    "inactive": 0
  },
  "NE": {
    "jurisdictions": 93,
    "reported": 93,
    "total": 1263487,
    "active": 1190813,
    "inactive": 72674
  },
  "NH": {
    "jurisdictions": 320,
    "reported": 320,
    "total": 1008952,
    "active": 1008603,
    "inactive": 0
  },
  "NJ": {
    "jurisdictions": 21,
    "reported": 21,
    "total": 6630364,
    "active": 6066940,
    "inactive": 563424
  },
  "NM": {
    "jurisdictions": 33,
    "reported": 33,
    "total": 1415984,
    "active": 1254851,
    "inactive": 156424
  },
  "NV": {
    "jurisdictions": 17,
    "reported": 17,
    "total": 2256275,
    "active": 2052976,
    "inactive": 202810
  },
  "NY": {
    "jurisdictions": 62,
    "reported": 62,
    "total": 13579416,
    "active": 12429981,
    "inactive": 1149435
  },
  "OH": {
    "jurisdictions": 88,
    "reported": 88,
    "total": 8074098,
    "active": 7054966,
    "inactive": 983368
  },
  "OK": {
    "jurisdictions": 77,
    "reported": 77,
    "total": 2442211,
    "active": 2095952,
    "inactive": 346259
  },
  "OR": {
    "jurisdictions": 36,
    "reported": 36,
    "total": 3060374,
    "active": 3060374,
    "inactive": 0
  },
  "PA": {
    "jurisdictions": 67,
    "reported": 67,
    "total": 9175133,
    "active": 8407874,
    "inactive": 767259
  },
  "PR": {
    "jurisdictions": 1,
    "reported": 1,
    "total": 1987317,
    "active": 1987317,
    "inactive": 0
  },
  "RI": {
    "jurisdictions": 39,
    "reported": 39,
    "total": 792075,
    "active": 734885,
    "inactive": 57190
  },
  "SC": {
    "jurisdictions": 46,
    "reported": 46,
    "total": 3851187,
    "active": 3417493,
    "inactive": 433694
  },
  "SD": {
    "jurisdictions": 66,
    "reported": 66,
    "total": 690306,
    "active": 627248,
    "inactive": 63058
  },
  "TN": {
    "jurisdictions": 95,
    "reported": 95,
    "total": 4825601,
    "active": 4458851,
    "inactive": 366750
  },
  "TX": {
    "jurisdictions": 254,
    "reported": 254,
    "total": 18623931,
    "active": 16611078,
    "inactive": 2012853
  },
  "UT": {
    "jurisdictions": 29,
    "reported": 29,
    "total": 2039862,
    "active": 1793182,
    "inactive": 246658
  },
  "VA": {
    "jurisdictions": 133,
    "reported": 133,
    "total": 6380686,
    "active": 5898922,
    "inactive": 481764
  },
  "VI": {
    "jurisdictions": 1,
    "reported": 1,
    "total": 56304,
    "active": 31171,
    "inactive": 25133
  },
  "VT": {
    "jurisdictions": 247,
    "reported": 247,
    "total": 500986,
    "active": 460415,
    "inactive": 40571
  },
  "WA": {
    "jurisdictions": 39,
    "reported": 39,
    "total": 5597156,
    "active": 5013112,
    "inactive": 520000
  },
  "WI": {
    "jurisdictions": 1851,
    "reported": 1851,
    "total": 3933068,
    "active": 3933068,
    "inactive": 0
  },
  "WV": {
    "jurisdictions": 55,
    "reported": 55,
    "total": 1210415,
    "active": 1118468,
    "inactive": 91947
  },
  "WY": {
    "jurisdictions": 23,
    "reported": 23,
    "total": 296960,
    "active": 296960,
    "inactive": 0
  }
};
